const products = [
  {
    id: 1,
    name: "Fuji Apples",
    category: "Produce",
    tags: ["fruit", "produce", "fresh", "snack"],
    price: "$1.29/lb",
    image: "images/products/product_01.jpg",
  },
  {
    id: 2,
    name: "Navel Oranges",
    category: "Produce",
    tags: ["fruit", "produce", "fresh", "citrus", "snack"],
    price: "$0.99/ea",
    image: "images/products/product_02.jpg",
  },
  {
    id: 3,
    name: "Key Limes",
    category: "Produce",
    tags: ["fruit", "produce", "fresh", "citrus"],
    price: "$0.49/ea",
    image: "images/products/product_03.jpg",
  },
  {
    id: 4,
    name: "Bananas",
    category: "Produce",
    tags: ["fruit", "produce", "fresh", "snack"],
    price: "$0.29/ea",
    image: "images/products/product_04.jpg",
  },
  {
    id: 5,
    name: "Roma Tomatoes",
    category: "Produce",
    tags: ["vegetable", "produce", "fresh"],
    price: "$1.49/lb",
    image: "images/products/product_05.jpg",
  },
  {
    id: 6,
    name: "Romaine Lettuce",
    category: "Produce",
    tags: ["vegetable", "produce", "fresh", "salad"],
    price: "$1.99/ea",
    image: "images/products/product_06.jpg",
  },
  {
    id: 7,
    name: "Yuca Root",
    category: "Produce",
    tags: ["vegetable", "produce", "fresh", "root vegetable"],
    price: "$0.89/lb",
    image: "images/products/product_07.jpg",
  },
  {
    id: 8,
    name: "Bell Peppers",
    category: "Produce",
    tags: ["vegetable", "produce", "fresh"],
    price: "$1.29/ea",
    image: "images/products/product_08.jpg",
  },
  {
    id: 9,
    name: "Chicken Leg Quarters",
    category: "Meat",
    tags: ["meat", "poultry", "chicken", "protein"],
    price: "$5.99/lb",
    image: "images/products/product_09.jpg",
  },
  {
    id: 10,
    name: "Chicken Breast",
    category: "Meat",
    tags: ["meat", "poultry", "chicken", "protein", "lean"],
    price: "$7.99/lb",
    image: "images/products/product_10.jpg",
  },
  {
    id: 11,
    name: "Ground Beef (80/20)",
    category: "Meat",
    tags: ["meat", "beef", "protein"],
    price: "$6.99/lb",
    image: "images/products/product_11.jpg",
  },
  {
    id: 12,
    name: "Atlantic Salmon",
    category: "Seafood",
    tags: ["seafood", "fish", "protein", "omega-3"],
    price: "$12.99/lb",
    image: "images/products/product_12.jpg",
  },
  {
    id: 13,
    name: "Canned Tuna",
    category: "Canned Goods",
    tags: ["canned", "seafood", "fish", "protein", "pantry"],
    price: "$2.10/ea",
    image: "images/products/product_13.jpg",
  },
  {
    id: 14,
    name: "Canned Black Beans",
    category: "Canned Goods",
    tags: ["canned", "beans", "protein", "pantry", "vegan"],
    price: "$1.10/ea",
    image: "images/products/product_14.jpg",
  },
  {
    id: 15,
    name: "Canned Chickpeas",
    category: "Canned Goods",
    tags: ["canned", "beans", "protein", "pantry", "vegan"],
    price: "$1.15/ea",
    image: "images/products/product_15.jpg",
  },
  {
    id: 16,
    name: "Coconut Milk",
    category: "Canned Goods",
    tags: ["canned", "dairy-free", "pantry", "vegan"],
    price: "$2.75/ea",
    image: "images/products/product_16.jpg",
  },
  {
    id: 17,
    name: "Firm Tofu",
    category: "Dairy & Alternatives",
    tags: ["protein", "vegan", "vegetarian", "soy"],
    price: "$2.99/ea",
    image: "images/products/product_17.jpg",
  },
  {
    id: 18,
    name: "Greek Yogurt",
    category: "Dairy & Alternatives",
    tags: ["dairy", "protein", "snack"],
    price: "$4.99/ea",
    image: "images/products/product_18.jpg",
  },
  {
    id: 19,
    name: "Sourdough Loaf",
    category: "Bakery",
    tags: ["bread", "bakery", "pantry"],
    price: "$5.99/ea",
    image: "images/products/product_19.jpg",
  },
  {
    id: 20,
    name: "Extra Virgin Olive Oil",
    category: "Pantry",
    tags: ["oil", "pantry", "vegan", "cooking"],
    price: "$10.99/ea",
    image: "images/products/product_20.jpg",
  },
];

const tags = [
  "fruit",
  "vegetable",
  "produce",
  "fresh",
  "citrus",
  "snack",
  "salad",
  "root vegetable",
  "meat",
  "poultry",
  "chicken",
  "protein",
  "lean",
  "beef",
  "seafood",
  "fish",
  "omega-3",
  "canned",
  "beans",
  "pantry",
  "vegan",
  "dairy-free",
  "dairy",
  "soy",
  "vegetarian",
  "bread",
  "bakery",
  "oil",
  "cooking",
];
